jobs:
  test-container-deploy:
    name: Test Deploy to a Container
    run_when:
      'on personal integration branch':
        type: branch
        include_match: ^[a-z]{2}_master$
        exclude_match: '^.*no-ci.*$'
    context:
      include:
        - path: container-test/cider-ci/context.yml
          submodule: [deploy]


