jobs:
  import-v3-to-v4-via-ci:
    depends_on:
      'only enable this when branch matches':
        type: branch
        include_match: ^import-v3-to-v4-via-ci$
    name: Import data v3 to v4 prod via CI
    priority: 1
    run_when:
      'nightly':
        type: cron
        value: '45 16 * * *'
        branch_include_match: ^master$
        rerun: true
    context:
      include:
        - path: cider-ci/shared/main-context.yml
          submodule: [legacy]
      tasks:
        import:
          include:
            - path: cider-ci/task-components/database.yml
              submodule: [legacy]
            - path: cider-ci/task-components/bundle-rspec-ruby.yml
              submodule: [legacy]
          git_options:
            submodules:
              include_match: ^.*$
          load: 5 # we need lots of RAM
          max_trials: 1
          traits:
            g2016: true
          exclusive_global_resources:
            "zhdk-leihs-prod.ruby.zhdk.ch": true
          scripts:
            test:
              body: exit 0
            fetch:
              timeout: 2 Hours
              body: |
                set -euxo
                cd deploy
                ansible-playbook fetch-v3-data_play.yml \
                  --ssh-common-args '-i ~/.ssh/zhdk_ci_executor_rsa' \
                  -i ../zhdk-inventory/prod-hosts
            unpack-images:
              start_when:
                fetch passed:
                  script_key: fetch
              body: |
                set -euxo
                cd legacy
                tar xvfz ../deploy/tmp/v3/files.tar.gz
            import-and-dump:
              start_when:
                images-unpacked:
                  script_key: unpack-images
                database created:
                  script_key: create-database
              timeout: 6 hours
              body: |
                set -euxo
                if [ -d legacy ]; then cd legacy; fi
                export PATH=~/.rubies/$RUBY/bin:$PATH
                bundle exec rake db:migrate VERSION=100
                bundle exec rake leihs:dbio:import FILE=../deploy/tmp/v3/db_data.yml
                bundle exec rake db:migrate
                bundle exec rake db:pg:structure_and_data:dump FILE=${CIDER_CI_WORKING_DIR}/db.pgbin
            create-database:
              start_when:
                database configured:
                  script_key: configure-database
              body: |
                #!/usr/bin/env bash
                set -euxo
                createdb "$DATABASE"
            delete-database:
              start_when:
                images-unpacked:
                  script_key: import-and-dump
                  states: [aborted, defective, passed, failed, skipped]
            restore-dump:
              timeout: 1 Hours
              start_when:
                import-and-dump passed:
                  script_key: import-and-dump
              body: |
                set -euxo
                cd deploy
                ansible-playbook db-restore_play.yml \
                  --ssh-common-args '-i ~/.ssh/zhdk_ci_executor_rsa' \
                  -e database_dump_restore_file_path=${CIDER_CI_WORKING_DIR}/db.pgbin \
                  -i ../zhdk-inventory/prod-hosts

