jobs:
  sync-staging-db-with-prod:
    name: Sync staging DB with prod
    priority: 2
    context:
      tasks:
        sync:
          git_options:
            submodules:
              include_match: ^.*$
          exclusive_global_resources:
            "zhdk-leihs-staging.ruby.zhdk.ch": true
          traits:
            g2016: true
          scripts:
            fetch:
              body: |
                set -euxo
                cd deploy
                ansible-playbook fetch-latest-dump_play.yml \
                  --ssh-common-args '-i ~/.ssh/zhdk_ci_executor_rsa' \
                  -i ../zhdk-inventory/prod-hosts
            restore-dump:
              timeout: 1 Hours
              start_when:
                fetch passed:
                  script_key: fetch
                  states: [passed]
              body: |
                set -eux
                cd deploy
                export ANSIBLE_HOST_KEY_CHECKING=False
                ansible-playbook db-restore_play.yml \
                  --ssh-common-args '-i ~/.ssh/zhdk_ci_executor_rsa' \
                  -i ../zhdk-inventory/staging-hosts --limit zhdk-leihs-staging

