jobs:
  sync-test-db-with-prod:
    name: Sync test DB with prod
    priority: 2
    run_when:
      nightly:
        type: cron
        value: '0 3 * * *'
        branch_include_match: ^master$
        rerun: true
    context:
      tasks:
        sync:
          git_options:
            submodules:
              include_match: ^.*$
          exclusive_global_resources:
            "zhdk-leihs-test.ruby.zhdk.ch": true
          traits:
            g2016: true
          scripts:
            fetch:
              body: |
                set -euxo
                cd deploy
                export ANSIBLE_HOST_KEY_CHECKING=False
                ansible-playbook fetch-latest-dump_play.yml \
                  --ssh-common-args '-i ~/.ssh/zhdk_ci_executor_rsa' \
                  -i ../zhdk-inventory/prod-hosts
            restore-dump:
              timeout: 1 Hours
              start_when:
                fetch passed:
                  script_key: fetch
                  states: [passed]
              body: |
                set -eux
                cd deploy
                export ANSIBLE_HOST_KEY_CHECKING=False
                ansible-playbook db-restore_play.yml \
                  --ssh-common-args '-i ~/.ssh/zhdk_ci_executor_rsa' \
                  -i ../zhdk-inventory/test-hosts
